export const GET_PRODUCTS = 'GET_PRODUCTS';
export const PRODUCT_ERROR = 'PRODUCT_ERROR';
export const GET_PRODUCT = 'GET_PRODUCT';
export const CALCULATE_PAGER='CALCULATE_PAGER';
export const GET_CATEGORY='GET_CATEGORY';
export const LOADING_REQUEST='LOADING_REQUEST';

